name: smc-backend
region: nyc
services:
  - name: api
    github:
      repo: Mohammad-abdo/smc-eg
      branch: main
      deploy_on_push: true
    build_command: npm ci --production && npm run prisma:generate
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      # Add your database credentials here or in DigitalOcean dashboard
      # - key: DATABASE_URL
      #   value: ${DATABASE_URL}
      # - key: DB_HOST
      #   value: ${DB_HOST}
      # etc...


